### ISSUE TITLE
Problem retrieving objects with bucket name containing a dash `-`

### ISSUE THREAD

**Issue by ssiegel95** [IBM/ibm-cos-sdk-python#11]
Using client version 2.0.0:

If we use a bucket name with a dash `-` in it, we can view the bucket and objects within it using the web front end. 

```
`cos.list_buckets()
'Buckets': [{'CreationDate': datetime.datetime(2018, 8, 3, 7, 45, 52, 495000, tzinfo=tzlocal()),
   'Name': 'rai-data'},
 [snip for  brevity]
```

However, using the boto3 python client, a call to list_buckets shows it present but a call to list_objects results in following:

```cos.list_objects(Bucket='rai-data')

NoSuchBucket                              Traceback (most recent call last)
[snip for brevity]
NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjects operation: The specified bucket does not exist.```

**Comment by ssiegel95** [comment]
I don't think this has anything to do with dashes afterall. Something else is going on, not sure yet what.

**Comment by kvsnoufal** [comment]
> Using client version 2.0.0:
> 
> If we use a bucket name with a dash `-` in it, we can view the bucket and objects within it using the web front end.
> 
> ```
> `cos.list_buckets()
> 'Buckets': [{'CreationDate': datetime.datetime(2018, 8, 3, 7, 45, 52, 495000, tzinfo=tzlocal()),
>    'Name': 'rai-data'},
>  [snip for  brevity]
> ```
> However, using the boto3 python client, a call to list_buckets shows it present but a call to list_objects results in following:
> 
> ```
> 
> NoSuchBucket                              Traceback (most recent call last)
> [snip for brevity]
> NoSuchBucket: An error occurred (NoSuchBucket) when calling the ListObjects operation: The specified bucket does not exist.```
> ```

I'm facing the same issue..How did you resolve this?
