### ISSUE TITLE
ibm_boto3 list_objects not working in the local terminal

### ISSUE THREAD

**Issue by entheos37** [IBM/ibm-cos-sdk-python#2]
Hi @wbhuberIBM 

ibm_boto3 list_objects working in the IBM Data Platform Jupyter Notebook however,

ibm_boto3 list_objects not working in the local terminal.

#example code
`client.list_objects(Bucket=bucket)`

I was able to print out the client object using `print(client)`

But when I try the list_objects then `ConnectionRefusedError(61, 'Connection refused'))` happened.

![2018-01-14 1 43 50](https://user-images.githubusercontent.com/16621093/34908031-741cc442-f8cc-11e7-83a5-4d16108a8e80.png)

The reason for trying the ibm_boto3 in my local since I want to upload the folder from my local to the IBM Data Platform project. My local folder contains a lot of files so I want to use the ibm_boto3 sdk from my local terminal to upload easily.

I created the folder in the IBM Data Platform project using the jupyter notebook ipynb file but also when I tested the put_object in my local terminal it was not working which was the same situation for list_objects.

How can I run the list_objects in my local terminal?

I am using `Python 3.5.2 :: Anaconda 4.3.0 (x86_64)`

Much appreciated,

**Comment by cpcunningham** [comment]
Hi  entheos37

First try to confirm it on the server machine by issuing telnet to that port: 
telnet <server> <port>
If it is listening, it is able to respond.

Then can you give an example of the code that creates a connection to IBM COS

**Comment by entheos37** [comment]
Hi cpcunningham 
I got the answer from https://stackoverflow.com/questions/48247477/ibm-boto3-connection-refused-error/48270881#48270881 

I change the endpoint_url from https://s3-api.us-geo.objectstorage.service.networklayer.com which is the private endpoint to `https://s3-api.us-geo.objectstorage.softlayer.net` which is the right public endpoint url.

Much appreciated!
