### ISSUE TITLE
ibm_botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied

### ISSUE THREAD

**Issue by harshit777** [IBM/ibm-cos-sdk-python#27]
ibm_botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied

Getting this issue since last two days, checked the credentials and all the keys. Not able to find the error.

**Comment by paul-carron** [comment]
@harshit777 How are you authenticating? Is ListBuckets the only operation that causes that error? If it previously worked has anything changed in your code or on the bucket?

**Comment by paul-carron** [comment]
@harshit777 Is this still an issue?

**Comment by harshit777** [comment]
@paul-carron issue has been resolved as there were some unresolved issues, I recreated the credentials and it worked fine

**Comment by paul-carron** [comment]
Thanks @harshit777 

#closed

**Comment by paul-carron** [comment]
@harshit777 can you please close this ticket?
