### ISSUE TITLE
Can't Install Aspera Python Package cos-aspera

### ISSUE THREAD

**Issue by thevicross** [IBM/ibm-cos-sdk-python#29]
Receiving error attempting to install package:

sudo pip3 install cos-aspera
Collecting cos-aspera
  Could not find a version that satisfies the requirement cos-aspera (from versions: )
No matching distribution found for cos-aspera

Using Windows 10 WLS Ubuntu 18.0.4 and Python3.7

**Comment by thevicross** [comment]
So, Python 3.6.8 is not supported yet either?

**Comment by cpcunningham** [comment]
aspera is supported on python 3.6.x

**Comment by mathieu-holl-ibm** [comment]
@thevicross if there's anything else you need, let us know, otherwise, we'll close this ticket.

**Comment by thevicross** [comment]
Thanks, please close.
