### ISSUE TITLE
Can't Install Aspera Python Package cos-aspera on power machines

### ISSUE THREAD

**Issue by shobhit0511** [IBM/ibm-cos-sdk-python#30]
Receiving error attempting to install package:

sudo pip install cos-aspera
Collecting cos-aspera
Could not find a version that satisfies the requirement cos-aspera (from versions: )
No matching distribution found for cos-aspera

ENV :
RHEL 7.6 UBI image
Python 2.7 & Python 3.6

**Comment by wbhuberIBM** [comment]
@shobhit0511 - 

Python 2.7 is no longer supported ([retired](https://www.python.org/dev/peps/pep-0373/)).  Can you do a ```python --version``` to indicate which minor version of python you are running for 3.6?  Could you also try checking if ```pip3``` works for you?

**Comment by shobhit0511** [comment]
@wbhuberIBM python 3.6.8

**Comment by wbhuberIBM** [comment]
@shobhit0511, after digging up some more, ```cos-aspera``` is not supported on RHEL, only ubuntu, see the following supported platforms:
https://cloud.ibm.com/docs/services/cloud-object-storage?topic=cloud-object-storage-aspera#aspera-sdk-platforms

Can you switch over to use ubuntu?

**Comment by shobhit0511** [comment]
@wbhuberIBM we are getting error for python not for OS packages :

> from ibm_s3transfer.aspera.manager import AsperaTransferManager
File "/usr/lib/python2.7/site-packages/ibm_s3transfer/aspera/manager.py", line 36, in <module>
    from ibm_s3transfer.aspera.futures import AsperaTransferCoordinator
  File "/usr/lib/python2.7/site-packages/ibm_s3transfer/aspera/futures.py", line 29, in <module>
    raise ImportError("Aspera SDK not installed")
ImportError: Aspera SDK not installed

**Comment by shobhit0511** [comment]
on py-pi repo this package is available only for :
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/10229426/73377564-3f969a80-42e5-11ea-8fdd-0a29ff4ff873.png">

**Comment by shobhit0511** [comment]
I need it for ppc64le too.

**Comment by wbhuberIBM** [comment]
@shobhit0511 - 
The COS SDK (the repo that is based here) uses Aspera libraries (```cos-aspera```) underneath that are platform dependent and that the Aspera libraries currently do not have support for the platform of interest.  We will bring this up with the Aspera team and get back to you.

To track this internally: CSAFE-66078

**Comment by rtveitch** [comment]
Closing this ticket for now; power architecture is on the backlog but there is currently no planned support for this platform.
