### ISSUE TITLE
Always get 404 Error with samples

### ISSUE THREAD

**Issue by jmbuiles** [IBM/ibm-cos-sdk-python#33]
CLIENT ERROR: An error occurred (404) when calling the ListObjects operation: Not Found

get_bucket_contents method

All parameters are configured according to the docs and there are no authentication errors.

**Comment by wbhuberIBM** [comment]
@jmbuiles - can you share the client creation code here?  What python version and COS SDK version are you running?  What platform?

**Comment by cloudpitchford** [comment]
I'll look for comments and replies here…

**Comment by wbhuberIBM** [comment]
Closing this issue since we have not yet gotten replies from @jmbuiles for two weeks.
