### ISSUE TITLE
Improve document and env. setup process of the error caused by missing `coverage` module

### ISSUE THREAD

**Issue by synergit** [IBM/ibm-cos-sdk-python#34]
> python scripts/ci/run-tests
nose.plugins.cover: ERROR: Coverage not available: unable to import coverage module

Fix: need install coverage `pip install coverage` because coverage plugin depends on separate coverage module, which is not a nose's dependency https://stackoverflow.com/a/14488761

Please improve document and env. setup process.

**Comment by synergit** [comment]
Looks like `python scripts/ci/install` takes care of the `coverage` installation. 

It is up to you if you want to close the ticket. Thank you.

**Comment by wbhuberIBM** [comment]
@synergit - yes, in order to run ```scripts/ci/run-tests```, you'd need to run the ```python scripts/ci/install``` that would then install the ```coverage``` package.  Thanks.
