### ISSUE TITLE
ibm-cos-sdk-python readme link is broken

### ISSUE THREAD

**Issue by powellquiring** [IBM/ibm-cos-sdk-python#44]
![image](https://user-images.githubusercontent.com/6932057/132743302-27126213-a430-4172-b204-d7321ca024ff.png)

I'm having trouble getting started...

The link for using python is https://cloud.ibm.com/docs/services/cloud-object-storage/libraries/python.html#using-python
maybe it should be https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-python

**Comment by IBMeric** [comment]
Thank you for this report. The readme link you cited is not broken but for me took additional to load. However, I agree the second link is more suitable, and we will make an update when we publish our next release.

**Comment by IBMeric** [comment]
We have resolved this issue with the release of 2.11.0. Can you verify and close this ticket?

**Comment by IBMeric** [comment]
Closing this ticket as resolved.
