### ISSUE TITLE
No ibm_boto3 module while installing package in bluemix with python 3.6.2

### ISSUE THREAD

**Issue by wilczogon** [IBM/ibm-cos-sdk-python#5]
I was trying to install ibm-cos-sdk on bluemix with python 3.6.2. It appeared that only available version there is 1.4.5 and I received error that there is no module ibm_boto3.

When I changed to python 3.6.1 it started working.

**Comment by cpcunningham** [comment]
We have tested the sdk on a number of different versions of python.
I will run regression tests using python 3.6.2 and check the results.

**Comment by cpcunningham** [comment]
I have run the regression tests without issue using python 3.6.2.
Can you  give details of how you instaledl ibm_boto on 3.6.2 and what app you are running.
Also the output of pip freeze would ,help..

**Comment by wilczogon** [comment]
I mean the environment on bluemix - not normal environment. Probably the
problem is not in python version itself but with bluemix configuration for
python version = 3.6.2

07.03.2018 16:28 "cpcunningham" <notifications@github.com> napisał(a):

**Comment by smcgrath-IBM** [comment]
A new issue has been created for this under object-storage
https://github.ibm.com/objectstore/objectstorage-issues/issues/278
