### ISSUE TITLE
Collaboration/Contribution for Great Expectations support of IBM Object Storage

### ISSUE THREAD

**Issue by rdodev** [IBM/ibm-cos-sdk-python#53]
Hey folks 👋 

We have some users of [GX](https://github.com/great-expectations/great_expectations) who have their data in IBM Cloud Object Store. GX supports AWS S3 via `boto3`; however, there are some differences we don't fully understand between what `boto` does and what `ibm-boto` does that's causing fatal issues when trying to list and retrieve objects from IBMCOS. We would like to see if you would be willing to engage with us collaborating/contributing for a solution to this issue. Thanks!

**Comment by avinash1IBM** [comment]
Hello @rdodev, 
Can you share more issue details like error details and sample code that you are trying which is causing the issue. We will take a look and will help you in fixing it.

**Comment by rdodev** [comment]
Hey @avinash1IBM 

Thanks for prompt response. This [issue](https://github.com/great-expectations/great_expectations/issues/6506) is a good example of what users are experiencing.

**Comment by avinash1IBM** [comment]
Hello @rdodev ,
Thanks for sharing the issue. After going through the above issue, here are some of the observations/findings 
1. The user who reported the above clearly explained that GX code is constructing url on other cloud provider and is ignoring specified url provided. I see a mismatch here. If the user says that they want to connect to IBM COS instead of other cloud providers, the endpoint url that must be specified should be among [these](https://cloud.ibm.com/docs/cloud-object-storage?topic=cloud-object-storage-endpoints#endpoints). So your code should either create an url based on the service provider or it should take user specified endpoint url into consideration.

**Comment by rdodev** [comment]
@avinash1IBM aside from URL construction, is there a difference between standard `boto3` and the the fork included in this SDK?

**Comment by avinash1IBM** [comment]
There is one more difference and for this use case that user mentioned, it is not applicable. But this is the difference.
IBM Cloud object storage has 2 types of credentials for authentication
1. IAM Credentials(apiKey and serviceInstanceId)
2. HMAC credentials(accessKey and SecretAccessKey)
As long as a user uses hmac credentials to connect to IBM COS with other cloud provider's sdk, endpoint url is the only thing that needs to be checked, but if the user uses IAM Credentials, they need to use IBM botocore sdk for that purpose.

**Comment by avinash1IBM** [comment]
There is one more difference and for this use case that user mentioned, it is not applicable. But this is the difference.
IBM Cloud object storage has 2 types of credentials for authentication
1. IAM Credentials(apiKey and serviceInstanceId)
2. HMAC credentials(accessKey and SecretAccessKey)
As long as a user uses hmac credentials to connect to IBM COS with other cloud provider's sdk, endpoint url is the only thing that needs to be checked, but if the user uses IAM Credentials, they need to use IBM botocore sdk for that purpose.

**Comment by rdodev** [comment]
> There is one more difference and for this use case that user mentioned, it is not applicable. But this is the difference. IBM Cloud object storage has 2 types of credentials for authentication
> 
> 1. IAM Credentials(apiKey and serviceInstanceId)
> 2. HMAC credentials(accessKey and SecretAccessKey)
>    As long as a user uses hmac credentials to connect to IBM COS with other cloud provider's sdk, endpoint url is the only thing that needs to be checked, but if the user uses IAM Credentials, they need to use IBM botocore sdk for that purpose.

Thanks for that. Appreciate the response. I'll go back to my team and present these answers.

**Comment by avinash1IBM** [comment]
Closing as resolved
