### ISSUE TITLE
With ibm-cos-sdk-python SDK intermittently getting "Connection closed error"

### ISSUE THREAD

**Issue by djain34** [IBM/ibm-cos-sdk-python#57]
Code :
`
from ibm_boto3 import resource, client`
`
self.s3 = client(  # type: ignore
            "s3",
            ibm_service_instance_id=client_config.cos_resource_instance_id,  # type: ignore
            endpoint_url=client_config.cos_endpoint_url,  # type: ignore
            token_manager=self._token_manager,
            config=S3Config(
                signature_version="oauth",
                max_pool_connections=client_config.parallelism,  # type: ignore
                connect_timeout=client_config.connect_timeout,
                read_timeout=client_config.read_timeout,
                retries={"max_attempts": client_config.retries_max_attempts},
            ),
        )`
        `paginator = self.s3.get_paginator("list_objects_v2")`
            `return SuccessResp(_page_fn(paginator))
            `
            
Error :
`Connection was closed before we received a valid response from endpoint URL: "https://s3.us-south.cloud-object-storage.appdomain.cloud/test-obs-vpc-eventing-2rep-perf?list-type=2&prefix=failure_obs_events_lifecycle_events_0.6.0%2Fregion%3Dsouth_2rep%2Fzone%3Dmzone7102%2Fwindow%3D2023072802&max-keys=1000&encoding-type=url".`

I couldn't attach the logs here.

Please ping me for more logs , I will send in email .
`Email Id : Deepti.Jain1@ibm.com`

**Comment by avinash1IBM** [comment]
Communication is happening via an internal channel to analyze the logs

**Comment by avinash1IBM** [comment]
Closing this as resolved
