### ISSUE TITLE
No matching distribution found for ibm-cos-sdk==2.13.5  on doing docker containerised builds with python3

### ISSUE THREAD

**Issue by rganeshpsgcs** [IBM/ibm-cos-sdk-python#62]
after using the latest **ibm-cos-sdk==2.13.5** dependency w.r.t. previous issue 
https://github.com/IBM/ibm-cos-sdk-python/issues/61#issuecomment-2157217471 

`#20 [16/16] RUN pip3 install -r  /mongo-scripts/requirements.txt
#20 1.072 Collecting ibm-cos-sdk==2.13.5 (from -r /mongo-scripts/requirements.txt (line 1))
#20 1.170   Could not find a version that satisfies the requirement ibm-cos-sdk==2.13.5 (from -r /mongo-scripts/requirements.txt (line 1)) (from versions: 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.0, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6.0, 2.6.2, 2.6.3, 2.7.0, 2.8.0, 2.9.0, 2.10.0, 2.11.0, 2.12.0, 2.12.1, 2.12.2, 2.13.0, 2.13.1, 2.13.2, 2.13.3, 2.13.4)
#20 1.170 No matching distribution found for ibm-cos-sdk==2.13.5 (from -r /mongo-scripts/requirements.txt (line 1))
#20 ERROR: process "/bin/sh -c pip3 install -r  /mongo-scripts/requirements.txt" did not complete successfully: exit code: 1`
`------
 > [16/16] RUN pip3 install -r  /mongo-scripts/requirements.txt:
#20 1.072 Collecting ibm-cos-sdk==2.13.5 (from -r /mongo-scripts/requirements.txt (line 1))
#20 1.170   **Could not find a version that satisfies the requirement ibm-cos-sdk==2.13.5** (from -r /mongo-scripts/requirements.txt (line 1)) (from versions: 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.1.1, 1.1.2, 1.2.0, 1.2.1, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.0, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6.0, 2.6.2, 2.6.3, 2.7.0, 2.8.0, 2.9.0, 2.10.0, 2.11.0, 2.12.0, 2.12.1, 2.12.2, 2.13.0, 2.13.1, 2.13.2, 2.13.3, 2.13.4)
#20 1.170 No matching distribution found for ibm-cos-sdk==2.13.5 (from -r /mongo-scripts/requirements.txt (line 1))`

python version is 

```
`RUN apt-get update && apt-get install -y \
    ca-certificates \
    python3 \
    python3-pip \

RUN pip3 install -r  /mongo-scripts/requirements.txt`
```

Pls let us know how to resolve this error. looks like the latest version of image is not available in the docker repository for consumption for doing containerised builds.

**Comment by IBMalok** [comment]
Closing since it is not an SDK issue. 
Thanks.
