### ISSUE TITLE
IBM Cloud Upcoming Security Update - Removal of CBC Ciphers in Cloud Object Storage Service

### ISSUE THREAD

**Issue by tokra** [IBM/ibm-cos-sdk-python#65]
We received this email from IBM CLOUD: 
 Upcoming Security Update - Removal of CBC Ciphers in Cloud Object Storage Service

To maintain the highest standards of security for our cloud storage service, we will be updating our encryption protocols by removing support for certain ciphers. From 11 Dec 2024 through 12 Dec 2024 the IBM Cloud Object Storage team will be removing the Cipher Block Chaining (CBC) ciphers.

What to Expect 

This update impacts the following CBC ciphers:

TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256  
Removing these CBC ciphers aligns with industry best practices and reduces vulnerability to certain security threats, such as padding oracle attacks. After the maintenance window, connections to our S3 service must be established using modern ciphers that support Galois/Counter Mode (GCM).

Actions Required

To avoid any disruption in service, verify your applications, scripts, or clients do not rely on CBC ciphers. Update any affected configurations to use TLS-compatible GCM encryption ciphers before 11 Dec 2024. If no action is taken, clients relying on CBC ciphers may experience connection issues following the update.

Assistance and Additional Information

The following ciphers will continue to be available with IBM Cloud Object Storage:

TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
Please reach out to our support team if you have questions or need assistance updating your configurations. 

-----------------

# Q: ^Is current library supporting this ?

**Comment by avinash1IBM** [comment]
@tokra The above mentioned impacted CBC ciphers are not used in the python sdk. So it can be closed.

**Comment by tokra** [comment]
@avinash1IBM is it also same for NodeJS sdk ?
