### ISSUE TITLE
Broken link to API reference

### ISSUE THREAD

**Issue by mtn** [IBM/ibm-cos-sdk-python#9]
The link to the [API reference](https://console.bluemix.net/docs/services/cloud-object-storage/api-reference/about-compatibility-api.html). Looking around for a few seconds I didn't find what should replace it, so maybe it should be removed. 🎈

**Comment by hegdehr** [comment]
@wbhuberIBM Could you assign this to Nick Lange on the documentation team please? Thanks!

**Comment by vanessawrites** [comment]
Link is in the readme.md
Link should be https://console.bluemix.net/docs/services/cloud-object-storage/api-reference/about-api.html

I need permissions to this branch to make the update

**Comment by wbhuberIBM** [comment]
Tracking here: CSAFE-41308

**Comment by vijuhullur** [comment]
@vanessawrites - can you make the changes in stage env, once its in stage I can push it out to prod - thanks

**Comment by vijuhullur** [comment]
@wbhuberIBM - Would you be able to make this change in readme file in ibm-cos-sdk-python repo?

**Comment by zhuojc** [comment]
@vijuhullur yes we're releasing the fix in the upcoming patch.

**Comment by paul-carron** [comment]
@mtn this was fixed in release 2.1.3. Please close the issue.
